<a href="https://colab.research.google.com/github/MadhawaAponso/MachineLearning_AtoZ/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


## Importing the dataset

In [ ]:
#import dataset
dataset = pd.read_csv('Data.csv')
# Load the dataset from a CSV file named 'Data.csv' using pandas and store it in the variable 'dataset'

x = dataset.iloc[:, :-1].values
# Extract all the columns except the last one from the dataset.
# 'iloc' is used for integer-location based indexing.
# ':' means all rows, ':-1' means all columns except the last one.
# 'values' converts the selected part of the DataFrame to a NumPy array.
# This extracted data is stored in variable 'x'.

y = dataset.iloc[:, -1].values
# Extract the last column from the dataset.
# 'iloc[:, -1]' means all rows, and only the last column.
# 'values' converts this column to a NumPy array.
# This extracted data is stored in variable 'y'.


In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
# Import the SimpleImputer class from the sklearn.impute module.
# SimpleImputer is used to fill in missing values in a dataset.

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# Create an instance of the SimpleImputer class.
# 'missing_values=np.nan' specifies that the missing values in the dataset are represented as NaNs.
# 'strategy='mean'' specifies that the missing values should be replaced with the mean value of the corresponding column.

imputer.fit(x[:,1:3])# this calculate the mean
x[:,1:3]=imputer.transform(x[:,1:3]) # replace the missing values in dataset


In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
# Import the ColumnTransformer class from the sklearn.compose module.
# ColumnTransformer is used to apply different preprocessing steps to different subsets of features.

from sklearn.preprocessing import OneHotEncoder
# Import the OneHotEncoder class from the sklearn.preprocessing module.
# OneHotEncoder is used to encode categorical features as a one-hot numeric array.

# Create an instance of the ColumnTransformer class.
# 'transformers' is a list of (name, transformer, columns) tuples specifying the transformer objects to be applied to subsets of the data.
# [('encoder', OneHotEncoder(), [0])] specifies that the OneHotEncoder should be applied to the first column (index 0).
# 'remainder="passthrough"' specifies that the remaining columns (not specified in transformers) should be passed through without transformation.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder="passthrough")

# Apply the transformations to the dataset 'x' and convert the result to a NumPy array.
x = np.array(ct.fit_transform(x))
# 'fit_transform' fits the ColumnTransformer to the data and then transforms the data.
# 'np.array' converts the resulting transformed data to a NumPy array.


In [ ]:
print(x)

### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Import the LabelEncoder class from the sklearn.preprocessing module.
# LabelEncoder is used to encode target labels with value between 0 and n_classes-1.

le = LabelEncoder()
# Create an instance of the LabelEncoder class.

y = le.fit_transform(y)
# Fit the LabelEncoder instance to the target variable 'y' and transform it.
# 'fit_transform' first fits the LabelEncoder to the target variable 'y', finding all the unique classes.
# It then transforms 'y' by replacing each class with a corresponding integer label.
# The transformed target variable is stored back in 'y'.


In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2,random_state=1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#All the values in same range
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])
#If you were to fit the scaler separately on the test data, it might have different mean and standard deviation values, leading to inconsistency and potentially misleading results.




In [ ]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]


In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]
